@startuml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

' Заголовок диаграммы
title Диаграмма контекста - Банк 'Стандарт'

' Расположение элементов сверху вниз (опционально)
LAYOUT_TOP_DOWN()

' --- Акторы (люди) ---
Person_Ext(client, "Клиент", "Физическое лицо, пользуется услугами банка.")
Person(foManager, "Менеджер фронт-офиса", "Работает с клиентами в отделении.")
Person(boManager, "Менеджер бэк-офиса", "Обрабатывает документы, вносит данные в АБС.")
Person(callCenterOp, "Оператор кол-центра", "Принимает и совершает звонки.")
Person(digitalTeam, "Команда цифровой трансформации", "Развивает онлайн-каналы, ставит задачи разработчикам.")

' --- Граница для основных систем банка ---
System_Boundary(bank, "Банк Стандарт") {
    System(site, "Сайт банка", "PHP + React", "Предоставляет информацию, принимает заявки на депозит.")
    System(internetBank, "Интернет-банк", "ASP.NET MVC + MS SQL", "Управление счетами, в будущем - открытие депозитов.")
    System(abs, "АБС", "Oracle", "Основной учётный контур банка (депозиты, кредиты, счета).")
    System(cc, "Система кол-центра", "Java + PostgreSQL", "Внутренний кол-центр, обработка звонков.")
    System(telecom, "Telecom ", "Возможно Cisco", "Телефония для внутренних звонков.")
}

' --- Внешняя система ---
System_Ext(partnerCRM, "CRM партнёрского кол-центра", "Внешняя CRM", "Система подрядчика для обработки заявок.")

' --- Связи ---
Rel(client, site, "Заполняет заявку на депозит, узнаёт информацию")
Rel(client, internetBank, "Взаимодействует с личным кабинетом")
Rel(site, partnerCRM, "Отправляет заявку на депозит (API)")
Rel(callCenterOp, cc, "Работает с входящими/исходящими звонками")
Rel(foManager, abs, "Открывает депозиты офлайн в отделении")
Rel(boManager, abs, "Обрабатывает онлайн-заявки, вносит данные")
Rel(cc, telecom, "Маршрутизация звонков (внутренний контакт-центр)")
Rel(partnerCRM, callCenterOp, "Отображает новые заявки, даёт контактные данные клиента")
Rel(digitalTeam, site, "Развитие сайта, онлайн-продуктов")
Rel(digitalTeam, internetBank, "Доработка функционала интернет-банка")
@enduml